// ==========================================
// 📚 媽媽的題庫資料中心 (MOM'S DATABASE)
// 更新版：114學年下學期
// ==========================================

const DB = {
    hunter: {

        // --- 國語科：12課圈詞注音（康軒1下）---
        chinese_zhuyin: [
            // 第1課「看」
            { q: "需要",     a: "ㄒㄩ ㄧㄠˋ" },
            { q: "要求",     a: "ㄧㄠˋ ㄑㄧㄡˊ" },
            { q: "靜靜的",   a: "ㄐㄧㄥˋ ㄐㄧㄥˋ ㄉㄜ˙" },
            { q: "天空",     a: "ㄊㄧㄢ ㄎㄨㄥ" },
            { q: "白雲",     a: "ㄅㄞˊ ㄩㄣˊ" },
            { q: "開水",     a: "ㄎㄞ ㄕㄨㄟˇ" },
            { q: "蟲鳥",     a: "ㄔㄨㄥˊ ㄋㄧㄠˇ" },
            { q: "花草",     a: "ㄏㄨㄚ ㄘㄠˇ" },
            { q: "先後",     a: "ㄒㄧㄢ ㄏㄡˋ" },
            { q: "完成",     a: "ㄨㄢˊ ㄔㄥˊ" },
            { q: "再去",     a: "ㄗㄞˋ ㄑㄩˋ" },
            // 第2課「花園裡有什麼」
            { q: "聽一聽",   a: "ㄊㄧㄥ ㄧ ㄊㄧㄥ" },
            { q: "沒有",     a: "ㄇㄟˊ ㄧㄡˇ" },
            { q: "正在",     a: "ㄓㄥˋ ㄗㄞˋ" },
            { q: "唱著",     a: "ㄔㄤˋ ㄓㄜ˙" },
            { q: "輕快",     a: "ㄑㄧㄥ ㄎㄨㄞˋ" },
            { q: "歌曲",     a: "ㄍㄜ ㄑㄩˇ" },
            { q: "出來",     a: "ㄔㄨ ㄌㄞˊ" },
            { q: "新芽",     a: "ㄒㄧㄣ ㄧㄚˊ" },
            { q: "聞一聞",   a: "ㄨㄣˊ ㄧ ㄨㄣˊ" },
            { q: "身上",     a: "ㄕㄣ ㄕㄤˋ" },
            { q: "花香",     a: "ㄏㄨㄚ ㄒㄧㄤ" },
            { q: "我呢",     a: "ㄨㄛˇ ㄋㄜ˙" },
            // 第3課「媽媽的音樂會」
            { q: "開始",     a: "ㄎㄞ ㄕˇ" },
            { q: "再來",     a: "ㄗㄞˋ ㄌㄞˊ" },
            { q: "重重的",   a: "ㄓㄨㄥˋ ㄓㄨㄥˋ ㄉㄜ˙" },
            { q: "短短的",   a: "ㄉㄨㄢˇ ㄉㄨㄢˇ ㄉㄜ˙" },
            { q: "一陣",     a: "ㄧ ㄓㄣˋ" },
            { q: "過後",     a: "ㄍㄨㄛˋ ㄏㄡˋ" },
            { q: "好吃",     a: "ㄏㄠˇ ㄔ" },
            { q: "菜餚",     a: "ㄘㄞˋ ㄧㄠˊ" },
            { q: "上桌",     a: "ㄕㄤˋ ㄓㄨㄛ" },
            { q: "真好",     a: "ㄓㄣ ㄏㄠˇ" },
            { q: "年菜",     a: "ㄋㄧㄢˊ ㄘㄞˋ" },
            { q: "成就",     a: "ㄔㄥˊ ㄐㄧㄡˋ" },
            // 第4課「鞋」
            { q: "回家",     a: "ㄏㄨㄟˊ ㄐㄧㄚ" },
            { q: "把鞋脫下", a: "ㄅㄚˇ ㄒㄧㄝˊ ㄊㄨㄛ ㄒㄧㄚˋ" },
            { q: "爸爸",     a: "ㄅㄚˋ ㄅㄚ˙" },
            { q: "靠近",     a: "ㄎㄠˋ ㄐㄧㄣˋ" },
            { q: "見聞",     a: "ㄐㄧㄢˋ ㄨㄣˊ" },
            { q: "好像",     a: "ㄏㄠˇ ㄒㄧㄤˋ" },
            { q: "小船",     a: "ㄒㄧㄠˇ ㄔㄨㄢˊ" },
            { q: "港口",     a: "ㄍㄤˇ ㄎㄡˇ" },
            { q: "享受",     a: "ㄒㄧㄤˇ ㄕㄡˋ" },
            { q: "溫暖",     a: "ㄨㄣ ㄋㄨㄢˇ" },
            // 第5課「小種子快長大」
            { q: "問題",     a: "ㄨㄣˋ ㄊㄧˊ" },
            { q: "怎麼做",   a: "ㄗㄣˇ ㄇㄜ˙ ㄗㄨㄛˋ" },
            { q: "它們",     a: "ㄊㄚ ㄇㄣ˙" },
            { q: "才會",     a: "ㄘㄞˊ ㄏㄨㄟˋ" },
            { q: "需要",     a: "ㄒㄩ ㄧㄠˋ" },
            { q: "於是",     a: "ㄩˊ ㄕˋ" },
            { q: "澆水",     a: "ㄐㄧㄠ ㄕㄨㄟˇ" },
            { q: "陽光",     a: "ㄧㄤˊ ㄍㄨㄤ" },
            { q: "放學",     a: "ㄈㄤˋ ㄒㄩㄝˊ" },
            { q: "院子",     a: "ㄩㄢˋ ㄗ˙" },
            { q: "外公",     a: "ㄨㄞˋ ㄍㄨㄥ" },
            { q: "說話",     a: "ㄕㄨㄛ ㄏㄨㄚˋ" },
            { q: "陪伴",     a: "ㄆㄟˊ ㄅㄢˋ" },
            // 第6課「奶奶的小跟班」
            { q: "奶奶",     a: "ㄋㄞˇ ㄋㄞ˙" },
            { q: "跟隨",     a: "ㄍㄣ ㄙㄨㄟˊ" },
            { q: "上班",     a: "ㄕㄤˋ ㄅㄢ" },
            { q: "起床",     a: "ㄑㄧˇ ㄔㄨㄤˊ" },
            { q: "弟弟",     a: "ㄉㄧˋ ㄉㄧ˙" },
            { q: "她們",     a: "ㄊㄚ ㄇㄣ˙" },
            { q: "家家酒",   a: "ㄐㄧㄚ ㄐㄧㄚ ㄐㄧㄡˇ" },
            { q: "拿出",     a: "ㄋㄚˊ ㄔㄨ" },
            { q: "卡片",     a: "ㄎㄚˇ ㄆㄧㄢˋ" },
            { q: "給我",     a: "ㄍㄟˇ ㄨㄛˇ" },
            { q: "寫字",     a: "ㄒㄧㄝˇ ㄗˋ" },
            { q: "喜歡",     a: "ㄒㄧˇ ㄏㄨㄢ" },
            { q: "您好",     a: "ㄋㄧㄣˊ ㄏㄠˇ" },
            { q: "都是",     a: "ㄉㄡ ㄕˋ" },
            // 第7課「作夢的雲」
            { q: "作夢",     a: "ㄗㄨㄛˋ ㄇㄥˋ" },
            { q: "躺著",     a: "ㄊㄤˇ ㄓㄜ˙" },
            { q: "自己",     a: "ㄗˋ ㄐㄧˇ" },
            { q: "變成",     a: "ㄅㄧㄢˋ ㄔㄥˊ" },
            { q: "棉花糖",   a: "ㄇㄧㄢˊ ㄏㄨㄚ ㄊㄤˊ" },
            { q: "黑色",     a: "ㄏㄟ ㄙㄜˋ" },
            { q: "天鵝",     a: "ㄊㄧㄢ ㄜˊ" },
            { q: "變得",     a: "ㄅㄧㄢˋ ㄉㄜˊ" },
            { q: "更漂亮",   a: "ㄍㄥˋ ㄆㄧㄠˋ ㄌㄧㄤˋ" },
            // 第8課「妹妹的紅雨鞋」
            { q: "一雙",     a: "ㄧ ㄕㄨㄤ" },
            { q: "穿上",     a: "ㄔㄨㄢ ㄕㄤˋ" },
            { q: "雨滴",     a: "ㄩˇ ㄉㄧ" },
            { q: "玩遊戲",   a: "ㄨㄢˊ ㄧㄡˊ ㄒㄧˋ" },
            { q: "一顆顆",   a: "ㄧ ㄎㄜ ㄎㄜ" },
            { q: "珍珠",     a: "ㄓㄣ ㄓㄨ" },
            { q: "落下",     a: "ㄌㄨㄛˋ ㄒㄧㄚˋ" },
            { q: "水面",     a: "ㄕㄨㄟˇ ㄇㄧㄢˋ" },
            { q: "魚缸",     a: "ㄩˊ ㄍㄤ" },
            { q: "金魚",     a: "ㄐㄧㄣ ㄩˊ" },
            { q: "游泳",     a: "ㄧㄡˊ ㄩㄥˇ" },
            // 第9課「七彩的虹」
            { q: "彩虹",     a: "ㄘㄞˇ ㄏㄨㄥˊ" },
            { q: "太陽",     a: "ㄊㄞˋ ㄧㄤˊ" },
            { q: "國王",     a: "ㄍㄨㄛˊ ㄨㄤˊ" },
            { q: "大掃除",   a: "ㄉㄚˋ ㄙㄠˇ ㄔㄨˊ" },
            { q: "洗淨",     a: "ㄒㄧˇ ㄐㄧㄥˋ" },
            { q: "馬路",     a: "ㄇㄚˇ ㄌㄨˋ" },
            { q: "高高低低", a: "ㄍㄠ ㄍㄠ ㄉㄧ ㄉㄧ" },
            { q: "刷亮",     a: "ㄕㄨㄚ ㄌㄧㄤˋ" },
            { q: "大樹",     a: "ㄉㄚˋ ㄕㄨˋ" },
            { q: "葉子",     a: "ㄧㄝˋ ㄗ˙" },
            { q: "很認真",   a: "ㄏㄣˇ ㄖㄣˋ ㄓㄣ" },
            { q: "送禮",     a: "ㄙㄨㄥˋ ㄌㄧˇ" },
            // 第10課「和你在一起」
            { q: "草地",     a: "ㄘㄠˇ ㄉㄧˋ" },
            { q: "變化",     a: "ㄅㄧㄢˋ ㄏㄨㄚˋ" },
            { q: "有趣",     a: "ㄧㄡˇ ㄑㄩˋ" },
            { q: "長線",     a: "ㄔㄤˊ ㄒㄧㄢˋ" },
            { q: "風箏",     a: "ㄈㄥ ㄓㄥ" },
            { q: "升高",     a: "ㄕㄥ ㄍㄠ" },
            { q: "神奇",     a: "ㄕㄣˊ ㄑㄧˊ" },
            { q: "跑跑跳跳", a: "ㄆㄠˇ ㄆㄠˇ ㄊㄧㄠˋ ㄊㄧㄠˋ" },
            { q: "說說笑笑", a: "ㄕㄨㄛ ㄕㄨㄛ ㄒㄧㄠˋ ㄒㄧㄠˋ" },
            { q: "每件",     a: "ㄇㄟˇ ㄐㄧㄢˋ" },
            { q: "事情",     a: "ㄕˋ ㄑㄧㄥˊ" },
            // 第11課「生日快樂」
            { q: "生日",     a: "ㄕㄥ ㄖˋ" },
            { q: "今天",     a: "ㄐㄧㄣ ㄊㄧㄢ" },
            { q: "記得",     a: "ㄐㄧˋ ㄉㄜˊ" },
            { q: "下課時",   a: "ㄒㄧㄚˋ ㄎㄜˋ ㄕˊ" },
            { q: "知道嗎",   a: "ㄓ ㄉㄠˋ ㄇㄚ˙" },
            { q: "放學",     a: "ㄈㄤˋ ㄒㄩㄝˊ" },
            { q: "收到",     a: "ㄕㄡ ㄉㄠˋ" },
            { q: "一張",     a: "ㄧ ㄓㄤ" },
            { q: "祝福",     a: "ㄓㄨˋ ㄈㄨˊ" },
            { q: "第一次",   a: "ㄉㄧˋ ㄧ ㄘˋ" },
            { q: "謝謝",     a: "ㄒㄧㄝˋ ㄒㄧㄝ˙" },
            // 第12課「小黑」
            { q: "想要",     a: "ㄒㄧㄤˇ ㄧㄠˋ" },
            { q: "路燈",     a: "ㄌㄨˋ ㄉㄥ" },
            { q: "前面",     a: "ㄑㄧㄢˊ ㄇㄧㄢˋ" },
            { q: "快一點",   a: "ㄎㄨㄞˋ ㄧ ㄉㄧㄢˇ" },
            { q: "一半",     a: "ㄧ ㄅㄢˋ" },
            { q: "清楚",     a: "ㄑㄧㄥ ㄔㄨˇ" },
            { q: "停下來",   a: "ㄊㄧㄥˊ ㄒㄧㄚˋ ㄌㄞˊ" },
            { q: "休息",     a: "ㄒㄧㄡ ㄒㄧ" },
            { q: "一會兒",   a: "ㄧ ㄏㄨㄟˋ ㄦ˙" },
            { q: "幫忙",     a: "ㄅㄤ ㄇㄤˊ" },
            { q: "加油",     a: "ㄐㄧㄚ ㄧㄡˊ" },
            { q: "慢慢的",   a: "ㄇㄢˋ ㄇㄢˋ ㄉㄜ˙" },
        ],

        // --- 照樣寫短語題庫 ---
        // 格式：q=顯示題目框架, blank=空格位置提示, opts=選項(第一個是正確答案), lesson=課次
        phrase_patterns: [
            // 第1課：靜靜的看 → ＿＿的＿
            { lesson:1,  q: "（　　）的（　）",    hint: "例：靜靜的看",   opts: ["慢慢的走","快快的跑","輕輕的拉","重重的放"] },
            { lesson:1,  q: "（　　）的（　）",    hint: "例：靜靜的看",   opts: ["輕輕的說","慢慢的吃","快快的寫","靜靜的坐"] },
            // 第2課：小花（香香）的
            { lesson:2,  q: "小花（　　）的",      hint: "例：香香的",     opts: ["香香","甜甜","酸酸","辣辣"] },
            { lesson:2,  q: "檸檬（　　）的",      hint: "例：酸酸的",     opts: ["酸酸","甜甜","香香","辣辣"] },
            { lesson:2,  q: "天空中（　　）的月亮", hint: "例：彎彎的",     opts: ["彎彎","圓圓","高高","亮亮"] },
            { lesson:2,  q: "風箏飛到（　　）的天上", hint: "例：高高的",  opts: ["高高","遠遠","藍藍","大大"] },
            // 第3課：又香又好吃的菜
            { lesson:3,  q: "又（　）又（　　）的菜", hint: "例：又香又好吃", opts: ["香,好吃","軟,香甜","大,厚重","甜,好喝"] },
            { lesson:3,  q: "（輕快／重重）的歌聲",   hint: "選出正確的詞",  opts: ["輕快","重重","短短","長長"] },
            { lesson:3,  q: "椅子倒了，發出（　　）的聲響", hint: "選詞填空", opts: ["重重","輕輕","短短","長長"] },
            // 第4課：大大小小的鞋
            { lesson:4,  q: "（大大小小）的（　）",  hint: "例：大大小小的鞋", opts: ["鞋子","樹葉","月亮","花朵"] },
            { lesson:4,  q: "（細細長長）的（　）",  hint: "例：細細長長的線", opts: ["線","路","手","尾巴"] },
            { lesson:4,  q: "（高高低低）的（　）",  hint: "例：高高低低的山", opts: ["山","聲音","樹","樓梯"] },
            // 第5課：快快長大
            { lesson:5,  q: "（快快）（長大）→（緩緩）（　　）", hint: "照樣寫", opts: ["飄落","跑步","飛翔","跳躍"] },
            { lesson:5,  q: "（說說）（話）→（唱唱）（　）",     hint: "照樣寫", opts: ["歌","舞","書","跑"] },
            // 第6課：弟弟（拍）著（手）
            { lesson:6,  q: "弟弟（拍）著（手）→ 妹妹（　）著（眼）", hint: "照樣寫", opts: ["瞇","閉","睜","看"] },
            { lesson:6,  q: "弟弟（拿出）（卡片）→ 哥哥（爬上）（　　）", hint: "照樣寫", opts: ["樓梯","書包","椅子","桌子"] },
            // 第7課：作夢的雲、睡著的貓
            { lesson:7,  q: "（作夢）的（雲）→（睡著）的（　）", hint: "照樣寫", opts: ["貓","魚","鳥","狗"] },
            { lesson:7,  q: "（作夢）的（雲）→（慢跑）的（　）", hint: "照樣寫", opts: ["人","風","雲","雨"] },
            { lesson:7,  q: "哥哥跑得更（　），因此獲得好成績", hint: "選詞", opts: ["快","高","遠","好"] },
            // 第8課：一顆顆珍珠、一雙雙新鞋
            { lesson:8,  q: "（一顆顆）（珍珠）→（一把把）（　　）", hint: "照樣寫", opts: ["雨傘","糖果","石頭","鉛筆"] },
            { lesson:8,  q: "（一顆顆）（珍珠）→（一件件）（　　）", hint: "照樣寫", opts: ["衣服","書包","鞋子","帽子"] },
            { lesson:8,  q: "（走）過來、（走）過去 → （跑）過來、（跑）過（　）", hint: "照樣寫", opts: ["去","來","到","了"] },
            // 第9課：掃得很認真、聽得很專心
            { lesson:9,  q: "（掃）得（很認真）→（聽）得（　　　）", hint: "照樣寫", opts: ["很專心","很開心","很用力","很仔細"] },
            { lesson:9,  q: "（掃）得（很認真）→（看）得（　　　）", hint: "照樣寫", opts: ["好仔細","很努力","很快樂","很有趣"] },
            { lesson:9,  q: "（大大）（小小）→（高高）（　　）",      hint: "照樣寫", opts: ["低低","大大","圓圓","長長"] },
            // 第10課：說說笑笑、跑跑跳跳
            { lesson:10, q: "（說說笑笑）→（唱唱跳跳）→（　　　　）", hint: "照樣寫", opts: ["吃吃喝喝","開開心心","慢慢跑跑","跳跳唱唱"] },
            { lesson:10, q: "（拉）著（長線）（放風箏）→（拿）著（抹布）（　　）", hint: "照樣寫", opts: ["擦桌子","掃地板","洗碗盤","搬椅子"] },
            { lesson:10, q: "（我們）（說說笑笑）（好歡喜）→（他們）（吃吃喝喝）（　　）", hint: "照樣寫", opts: ["真開心","好快樂","很有趣","真好玩"] },
            // 第11課：傷心的哭了、開心的笑了
            { lesson:11, q: "（快樂）的（笑）了 → （傷心）的（　）了", hint: "照樣寫", opts: ["哭","跑","說","走"] },
            { lesson:11, q: "（快樂）的（笑）了 → （生氣）的（　）了", hint: "照樣寫", opts: ["走","哭","笑","跳"] },
            // 第12課：看誰跑得快、跳得高
            { lesson:12, q: "看誰（跑）得（快）→ 看誰（跳）得（　）", hint: "照樣寫", opts: ["高","遠","快","好"] },
            { lesson:12, q: "（我）幫（小黑）（加油）→（姐姐）幫（爺爺）（　　）", hint: "照樣寫", opts: ["搥背","加油","倒水","拿包"] },
            { lesson:12, q: "（我們）（跑）到（路燈下）→（大家）（爬）到（　　）", hint: "照樣寫", opts: ["山頂上","樹上面","公園裡","教室裡"] },
        ],

        // --- 造句題庫 ---
        // 格式：pattern=句型, example=例句, hint=提示, opts=選項(選一個完成句子)
        sentence_patterns: [
            // 第1課：先……再……
            { lesson:1,  pattern: "先……再……", example: "妹妹先打開紙盒，再喝了一口牛奶。",
              q: "我先（　　），再（　　）。", opts: [["洗手,吃飯"],["跑步,休息"],["寫作業,看電視"],["刷牙,睡覺"]] },
            { lesson:1,  pattern: "先……再……", example: "先把垃圾掃乾淨，再開始拖地。",
              q: "他先（　　），再（　　）。", opts: [["寫完功課,出去玩"],["吃完飯,洗碗"],["看完書,睡覺"],["刷完牙,喝水"]] },
            // 第3課：……就……
            { lesson:3,  pattern: "……就……", example: "媽媽回到家，妹妹就開心的撲進她的懷裡。",
              q: "哥哥回到家（　），就（　　）。", opts: [["後,寫功課"],["時,吃飯"],["前,洗手"],["裡,看書"]] },
            { lesson:3,  pattern: "……就……", example: "一陣音樂過後，好吃的菜就上桌了。",
              q: "放學（　），我就（　　）。", opts: [["後,回家"],["前,等車"],["時,唱歌"],["了,睡覺"]] },
            // 第5課：需要……才……
            { lesson:5,  pattern: "需要……才……", example: "姐姐需要專心練習彈琴，才能在演奏會上有好表現。",
              q: "種子需要（　　和　　），才會（　　）。", opts: [["水,陽光,長大"],["土,空氣,開花"],["雨,風,發芽"],["肥料,水,長高"]] },
            { lesson:5,  pattern: "……一起……", example: "每天早上，我和哥哥一起走路上學。",
              q: "我和（　　）一起（　　）。", opts: [["媽媽,買菜"],["同學,打球"],["弟弟,看書"],["爸爸,跑步"]] },
            // 第6課：也……、都……
            { lesson:6,  pattern: "也……", example: "我愛唱歌，姐姐也愛唱歌。",
              q: "我喜歡（　　），弟弟也（　　）。", opts: [["畫畫,喜歡畫畫"],["跑步,愛跑步"],["看書,想看書"],["游泳,去游泳"]] },
            { lesson:6,  pattern: "都……", example: "西瓜汁太好喝了，我和哥哥都喜歡喝。",
              q: "（　　）太（　　）了，大家都（　　）。", opts: [["這首歌,好聽,喜歡"],["蛋糕,好吃,想吃"],["天氣,熱,想喝冰水"],["故事,有趣,愛聽"]] },
            // 第7課：更……、把……
            { lesson:7,  pattern: "更……", example: "姐姐跑得很快，哥哥跑得更快。",
              q: "妹妹跑得很快，弟弟跑得（　）（　）。", opts: [["更,快"],["比,慢"],["非常,好"],["真的,遠"]] },
            { lesson:7,  pattern: "把……", example: "寒冷的北風把大地變得好冷啊！",
              q: "春天的陽光把（　　）變得（　　）。", opts: [["天氣,暖和"],["花朵,美麗"],["樹葉,綠色"],["小草,茂盛"]] },
            // 第8課：一……就……
            { lesson:8,  pattern: "一……就……", example: "我一回到家，就先複習今天上課的內容。",
              q: "我一（　　），就（　　）。", opts: [["放學,回家"],["起床,刷牙"],["吃完飯,洗碗"],["到學校,找朋友"]] },
            // 第9課：也……
            { lesson:9,  pattern: "也……", example: "哥哥喜歡跑步，也喜歡打羽毛球。",
              q: "媽媽喜歡（　　），也喜歡（　　）。", opts: [["唱歌,跳舞"],["看書,散步"],["做菜,園藝"],["畫畫,寫字"]] },
            // 第10課：都……
            { lesson:10, pattern: "都……", example: "妹妹的個性很開朗，每天都笑容滿面。",
              q: "弟弟很（　　），每天都（　　）。", opts: [["活潑,開心玩耍"],["乖巧,認真讀書"],["可愛,讓人喜歡"],["聰明,考高分"]] },
            // 第11課：會不會……
            { lesson:11, pattern: "會不會……", example: "天空突然烏雲密布，等一下會不會下雨呢？",
              q: "天氣這麼冷，明天會不會（　　）呢？", opts: ["下雪","下雨","颳風","放晴"] },
            { lesson:11, pattern: "這是我第一次……", example: "這是我第一次收到生日卡片，我好開心！",
              q: "這是我第一次（　　），我好（　　）！", opts: [["上台表演,緊張"],["學游泳,害怕"],["搭飛機,興奮"],["騎腳踏車,開心"]] },
            // 第12課：一開始……後來……
            { lesson:12, pattern: "一開始……後來……", example: "一開始，一道閃電劃破天空，後來雷聲響起，落下了大雨。",
              q: "一開始（　　），後來（　　）。", opts: [["天氣很晴朗,突然下起大雨"],["他跑在前面,慢下來等我"],["我很緊張,慢慢放鬆了"],["比賽很激烈,我方獲勝了"]] },
        ],

        // --- 英文科 ---
        english: [
            { q: "School", hint: "🏫", audio: "school" },
            { q: "Teacher", hint: "👩‍🏫", audio: "teacher" },
            { q: "Book", hint: "📖", audio: "book" },
            { q: "Pencil", hint: "✏️", audio: "pencil" },
            { q: "Bag", hint: "🎒", audio: "bag" },
            { q: "Eraser", hint: "🧼", audio: "eraser" },
            { q: "Ruler", hint: "📏", audio: "ruler" },
            { q: "Desk", hint: "🪑", audio: "desk" },
            { q: "Computer", hint: "💻", audio: "computer" },
            { q: "Head", hint: "💆", audio: "head" },
            { q: "Toe", hint: "🦶", audio: "toe" },
            { q: "Hand", hint: "✋", audio: "hand" },
            { q: "Knee", hint: "🦵", audio: "knee" },
            { q: "Eyes", hint: "👁️", audio: "eyes" },
            { q: "Nose", hint: "👃", audio: "nose" },
            { q: "Mouth", hint: "👄", audio: "mouth" },
            { q: "Ear", hint: "👂", audio: "ear" },
            { q: "Leg", hint: "🦵", audio: "leg" },
            { q: "Arm", hint: "💪", audio: "arm" },
            { q: "Lion", hint: "🦁", audio: "lion" },
            { q: "Monkey", hint: "🐵", audio: "monkey" },
            { q: "Elephant", hint: "🐘", audio: "elephant" },
            { q: "Snake", hint: "🐍", audio: "snake" },
            { q: "Dog", hint: "🐶", audio: "dog" },
            { q: "Cat", hint: "🐱", audio: "cat" },
            { q: "Rabbit", hint: "🐰", audio: "rabbit" },
            { q: "Tiger", hint: "🐯", audio: "tiger" },
            { q: "Giraffe", hint: "🦒", audio: "giraffe" },
            { q: "Zebra", hint: "🦓", audio: "zebra" },
            { q: "Horse", hint: "🐴", audio: "horse" },
            { q: "Cow", hint: "🐮", audio: "cow" },
            { q: "Pig", hint: "🐷", audio: "pig" },
            { q: "Bird", hint: "🐦", audio: "bird" },
            { q: "Fish", hint: "🐟", audio: "fish" },
            { q: "Bear", hint: "🐻", audio: "bear" },
            { q: "Clap", hint: "👏", audio: "clap" },
            { q: "Stomp", hint: "🦶", audio: "stomp" },
            { q: "Run", hint: "🏃", audio: "run" },
            { q: "Jump", hint: "🦘", audio: "jump" },
            { q: "Sit down", hint: "🪑", audio: "sit down" },
            { q: "Turn", hint: "🔄", audio: "turn" },
            { q: "Swim", hint: "🏊", audio: "swim" },
            { q: "Dance", hint: "💃", audio: "dance" },
            { q: "Sing", hint: "🎤", audio: "sing" },
            { q: "Sleep", hint: "😴", audio: "sleep" },
            { q: "Eat", hint: "🍽️", audio: "eat" },
            { q: "Monster", hint: "👹", audio: "monster" },
            { q: "Pumpkin", hint: "🎃", audio: "pumpkin" },
            { q: "Ghost", hint: "👻", audio: "ghost" },
            { q: "Santa", hint: "🎅", audio: "santa" },
            { q: "Gift", hint: "🎁", audio: "gift" },
            { q: "Snowman", hint: "⛄", audio: "snowman" },
            { q: "Red", hint: "🔴", audio: "red" },
            { q: "Blue", hint: "🔵", audio: "blue" },
            { q: "Green", hint: "🟢", audio: "green" },
            { q: "Yellow", hint: "🟡", audio: "yellow" },
            { q: "Orange", hint: "🟠", audio: "orange" },
            { q: "Purple", hint: "🟣", audio: "purple" },
            { q: "Pink", hint: "🩷", audio: "pink" },
            { q: "Black", hint: "⚫", audio: "black" },
            { q: "White", hint: "⚪", audio: "white" },
            { q: "Circle", hint: "⭕", audio: "circle" },
            { q: "Square", hint: "🟥", audio: "square" },
            { q: "Star", hint: "⭐", audio: "star" },
            { q: "Heart", hint: "❤️", audio: "heart" },
            { q: "Triangle", hint: "🔺", audio: "triangle" },
            { q: "Apple", hint: "🍎", audio: "apple" },
            { q: "Banana", hint: "🍌", audio: "banana" },
            { q: "Pizza", hint: "🍕", audio: "pizza" },
            { q: "Hamburger", hint: "🍔", audio: "hamburger" },
            { q: "Noodles", hint: "🍜", audio: "noodles" },
            { q: "Rice", hint: "🍚", audio: "rice" },
            { q: "Ice Cream", hint: "🍦", audio: "ice cream" },
            { q: "Cake", hint: "🍰", audio: "cake" },
            { q: "Milk", hint: "🥛", audio: "milk" },
            { q: "Water", hint: "💧", audio: "water" },
            { q: "Sun", hint: "☀️", audio: "sun" },
            { q: "Moon", hint: "🌙", audio: "moon" },
            { q: "Cloud", hint: "☁️", audio: "cloud" },
            { q: "Rain", hint: "🌧️", audio: "rain" },
            { q: "Snow", hint: "❄️", audio: "snow" },
            { q: "Flower", hint: "🌸", audio: "flower" },
            { q: "Tree", hint: "🌳", audio: "tree" },
            { q: "Daddy", hint: "👨", audio: "daddy" },
            { q: "Mommy", hint: "👩", audio: "mommy" },
            { q: "Baby", hint: "👶", audio: "baby" },
            { q: "Grandpa", hint: "👴", audio: "grandpa" },
            { q: "Grandma", hint: "👵", audio: "grandma" },
        ],

        // --- 數學科 (1下完整版) ---
        mathUnits: [
            // 原有單元（升級範圍）
            { id: "h_decomp", name: "分與合", desc: "10 可以分成…？", type: "decomp", range: 10 },
            { id: "h_seq",    name: "順序與多少", desc: "從左／右數第幾個", type: "seq", range: 10 },
            // 新單元
            { id: "h_add18",  name: "18以內加法", desc: "進位加法", type: "add", range: 18 },
            { id: "h_sub18",  name: "18以內減法", desc: "退位減法", type: "sub", range: 18 },
            { id: "h_num100", name: "數到100", desc: "+1 -1 +10 -10 比大小", type: "num100", range: 100 },
            { id: "h_money",  name: "錢幣換算", desc: "10元和1元", type: "money", range: 100 },
            { id: "h_add2d",  name: "二位數加法", desc: "28+4、35+13…", type: "add2d", range: 50 },
            { id: "h_sub2d",  name: "二位數減法", desc: "38-18、30-8…", type: "sub2d", range: 50 },
            { id: "h_clock",  name: "讀鐘錶", desc: "整點與半點", type: "clock", range: "half" },
            { id: "h_mix",    name: "期末大挑戰", desc: "綜合練習", type: "mix", range: 18 },
        ]
    },

    angus: {
        zhuyin: "ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦ".split(""),

        mathUnits: [
            { id: "a_count", name: "數數練習",  desc: "數數看有幾個？", type: "count", range: 20 },
            { id: "a_add",   name: "簡單加法",  desc: "5以內加法",     type: "add",   range: 5  },
            { id: "a_sub",   name: "簡單減法",  desc: "5以內減法",     type: "sub",   range: 5  },
            { id: "a_clock", name: "看時鐘",    desc: "長針指著12",    type: "clock", range: "full" },
        ],

        english: [
            { q: "Red",      hint: "🔴", audio: "red" },
            { q: "Blue",     hint: "🔵", audio: "blue" },
            { q: "Green",    hint: "🟢", audio: "green" },
            { q: "Yellow",   hint: "🟡", audio: "yellow" },
            { q: "Orange",   hint: "🟠", audio: "orange" },
            { q: "Purple",   hint: "🟣", audio: "purple" },
            { q: "Pink",     hint: "🩷", audio: "pink" },
            { q: "Black",    hint: "⚫", audio: "black" },
            { q: "White",    hint: "⚪", audio: "white" },
            { q: "Cat",      hint: "🐱", audio: "cat" },
            { q: "Dog",      hint: "🐶", audio: "dog" },
            { q: "Pig",      hint: "🐷", audio: "pig" },
            { q: "Duck",     hint: "🦆", audio: "duck" },
            { q: "Bear",     hint: "🐻", audio: "bear" },
            { q: "Fish",     hint: "🐟", audio: "fish" },
            { q: "Bird",     hint: "🐦", audio: "bird" },
            { q: "Horse",    hint: "🐴", audio: "horse" },
            { q: "Cow",      hint: "🐮", audio: "cow" },
            { q: "Sheep",    hint: "🐑", audio: "sheep" },
            { q: "Chicken",  hint: "🐔", audio: "chicken" },
            { q: "Rabbit",   hint: "🐰", audio: "rabbit" },
            { q: "Tiger",    hint: "🐯", audio: "tiger" },
            { q: "Lion",     hint: "🦁", audio: "lion" },
            { q: "Monkey",   hint: "🐵", audio: "monkey" },
            { q: "Elephant", hint: "🐘", audio: "elephant" },
            { q: "Zebra",    hint: "🦓", audio: "zebra" },
            { q: "Giraffe",  hint: "🦒", audio: "giraffe" },
            { q: "Snake",    hint: "🐍", audio: "snake" },
            { q: "Mouse",    hint: "🐭", audio: "mouse" },
            { q: "Apple",    hint: "🍎", audio: "apple" },
            { q: "Banana",   hint: "🍌", audio: "banana" },
            { q: "Milk",     hint: "🥛", audio: "milk" },
            { q: "Cake",     hint: "🍰", audio: "cake" },
            { q: "Egg",      hint: "🥚", audio: "egg" },
            { q: "Bread",    hint: "🍞", audio: "bread" },
            { q: "Water",    hint: "💧", audio: "water" },
            { q: "Juice",    hint: "🧃", audio: "juice" },
            { q: "Ice Cream",hint: "🍦", audio: "ice cream" },
            { q: "Cookie",   hint: "🍪", audio: "cookie" },
            { q: "Bus",      hint: "🚌", audio: "bus" },
            { q: "Car",      hint: "🚗", audio: "car" },
            { q: "Train",    hint: "🚂", audio: "train" },
            { q: "Plane",    hint: "✈️", audio: "plane" },
            { q: "Bike",     hint: "🚲", audio: "bike" },
            { q: "Sun",      hint: "☀️", audio: "sun" },
            { q: "Moon",     hint: "🌙", audio: "moon" },
            { q: "Star",     hint: "⭐", audio: "star" },
            { q: "Rain",     hint: "🌧️", audio: "rain" },
            { q: "Snow",     hint: "❄️", audio: "snow" },
            { q: "Flower",   hint: "🌸", audio: "flower" },
            { q: "Tree",     hint: "🌳", audio: "tree" },
            { q: "Daddy",    hint: "👨", audio: "daddy" },
            { q: "Mommy",    hint: "👩", audio: "mommy" },
            { q: "Baby",     hint: "👶", audio: "baby" },
            { q: "Ball",     hint: "⚽", audio: "ball" },
            { q: "Book",     hint: "📖", audio: "book" },
        ]
    }
};
